### ISSUE TITLE
Arch linux installation error?

### ISSUE THREAD

**Issue by ColtNovak** [uwu/neptune-installer#10]
running on hyprland
Downloads
❯ sudo -E ./neptune-installer-linux
Authorization required, but no authorization protocol specified

2024/11/05 01:06:37 Fyne error:  Unable to connect to session D-Bus
2024/11/05 01:06:37   Cause: write unix @: sendmsg: broken pipe
2024/11/05 01:06:37   At: /home/runner/go/pkg/mod/fyne.io/fyne/v2@v2.3.3/app/app_xdg.go:39
Authorization required, but no authorization protocol specified

2024/11/05 01:06:37 PlatformError: X11: Failed to open display :1
panic: NotInitialized: The GLFW library is not initialized

goroutine 1 [running, locked to thread]:
github.com/go-gl/glfw/v3.3/glfw.acceptError({0x0, 0x0, 0xc00029fbf0?})
	/home/runner/go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20221017161538-93cebf72946b/error.go:174 +0x1d9
github.com/go-gl/glfw/v3.3/glfw.panicError(...)
	/home/runner/go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20221017161538-93cebf72946b/error.go:185
github.com/go-gl/glfw/v3.3/glfw.CreateStandardCursor(0xaa53c0?)
	/home/runner/go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20221017161538-93cebf72946b/input.go:530 +0x45
fyne.io/fyne/v2/internal/driver/glfw.initCursors()
	/home/runner/go/pkg/mod/fyne.io/fyne/v2@v2.3.3/internal/driver/glfw/window_desktop.go:47 +0x5f
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).initGLFW.func1()
	/home/runner/go/pkg/mod/fyne.io/fyne/v2@v2.3.3/internal/driver/glfw/loop_desktop.go:27 +0x54
sync.(*Once).doSlow(0x203000?, 0x203000?)
	/opt/hostedtoolcache/go/1.19.13/x64/src/sync/once.go:74 +0xc2
sync.(*Once).Do(...)
	/opt/hostedtoolcache/go/1.19.13/x64/src/sync/once.go:65
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).initGLFW(0x467d40?)
	/home/runner/go/pkg/mod/fyne.io/fyne/v2@v2.3.3/internal/driver/glfw/loop_desktop.go:16 +0x45
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).createWindow.func1()
	/home/runner/go/pkg/mod/fyne.io/fyne/v2@v2.3.3/internal/driver/glfw/window.go:941 +0x4a
fyne.io/fyne/v2/internal/driver/glfw.runOnMain(0xc0003d6c30)
	/home/runner/go/pkg/mod/fyne.io/fyne/v2@v2.3.3/internal/driver/glfw/loop.go:61 +0x11d
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).createWindow(0xc0003d1340, {0xb5bb92, 0x11}, 0x1)
	/home/runner/go/pkg/mod/fyne.io/fyne/v2@v2.3.3/internal/driver/glfw/window.go:940 +0xe5
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).CreateWindow(0xc828d8?, {0xb5bb92?, 0x0?})
	/home/runner/go/pkg/mod/fyne.io/fyne/v2@v2.3.3/internal/driver/glfw/window.go:932 +0x25
fyne.io/fyne/v2/app.(*fyneApp).NewWindow(0x0?, {0xb5bb92?, 0x13c5258?})
	/home/runner/go/pkg/mod/fyne.io/fyne/v2@v2.3.3/app/app.go:69 +0x26
main.main()
	/home/runner/work/neptune-installer/neptune-installer/main.go:34 +0xb8

**Comment by yellowsink** [comment]
can other xwayland apps launch correctly on your setup?
